# Generated by Django 4.1.7 on 2023-04-30 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=10)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Polls_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(max_length=20)),
                ('Desc', models.TextField(max_length=20, null=True)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('Date_end', models.DateTimeField()),
                ('Is_active', models.BooleanField(default=True)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_voted', models.BooleanField(default=False)),
                ('the_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.choice_poll')),
                ('the_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.polls_details')),
                ('the_voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='choice_poll',
            name='poll_belongsto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.polls_details'),
        ),
    ]
